### ISSUE TITLE
Moar Pieces

### ISSUE THREAD

**Issue by BackOnTruck** [xiongyunuo/Fairy-Piece#1]
I'm I-I_I-I, whom the author just called suck. How daring he is!
Long story short, I don't expect him to design all pieces on [https://en.wikipedia.org/wiki/Fairy_chess_piece](url), but I would like the following pieces to be added:

- [x] Berolina Pawn: a pawn that moves diagonally and captures forward. Maybe it should be a somewhat twisted pawns?
- [x] Grasshopper: moves like a Q but must hop over another piece. Inverted Q should be OK?
- [x] Nightrider: a knight that moves multiple times in the same direction. Two N against each other should be good.
- [x] Checker / Checker King: #4PlayerCheckers

Finally if the mighty author fails to design all these before 2200, I'll offer assistance by spamming pull requests.

**Comment by xiongyunuo** [comment]
First comment (dumb issue demands a dumb response)

**Comment by xiongyunuo** [comment]
Mission accomplished
